import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API||'';
function App(){
 const[h,setH]=useState({}),[sym,setSym]=useState('RELIANCE'),[market,setMarket]=useState('NSE'),[signal,setSignal]=useState({signal:'HOLD',reason:'Waiting'}),[err,setErr]=useState(''),[bt,setBt]=useState(null),[running,setRunning]=useState(false);
 const[form,setForm]=useState({market:'NSE',symbols:'RELIANCE,TCS,INFY',start:'2020-01-01',end:'2026-01-01',interval:'1d',initial_capital:100000,brokerage_pct:0.03,slippage_pct:0.05,stop_pct:2,target_pct:4,allow_short:false});
 async function refresh(){try{let r=await fetch(API+'/api/health');setH(await r.json());let x=await fetch(API+'/api/signal/'+market+'/'+encodeURIComponent(sym));setSignal(await x.json());setErr('')}catch(e){setErr('Backend unavailable')}}
 useEffect(()=>{refresh();let i=setInterval(refresh,5000);return()=>clearInterval(i)},[market,sym]);
 async function control(path){await fetch(API+path,{method:'POST'});refresh()}
 async function runBacktest(e){e.preventDefault();setRunning(true);setBt(null);setErr('');try{const payload={...form,symbols:form.symbols.split(',').map(x=>x.trim()).filter(Boolean),initial_capital:Number(form.initial_capital),brokerage_pct:Number(form.brokerage_pct),slippage_pct:Number(form.slippage_pct),stop_pct:Number(form.stop_pct),target_pct:Number(form.target_pct)};const r=await fetch(API+'/api/backtest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Backtest failed');setBt(data)}catch(e){setErr(e.message)}finally{setRunning(false)}}
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 return <div className="app"><header><h1>Ichimoku Auto Trader</h1><span className="status">● {h.status||'offline'}</span></header><main>
 <section className="toolbar"><select value={market} onChange={e=>setMarket(e.target.value)}><option>NSE</option><option>NASDAQ</option></select><input value={sym} onChange={e=>setSym(e.target.value)} placeholder="Symbol"/><button onClick={()=>control('/api/control/start')}>Start</button><button onClick={()=>control('/api/control/stop')}>Stop</button><button className="danger" onClick={()=>control('/api/control/emergency-stop')}>EMERGENCY STOP</button></section>
 <section className="grid"><Card title="Signal"><b className="signal">{signal.signal}</b><p>{signal.reason}</p></Card><Card title="System"><p>Environment: {h.environment}</p><p>Auto trading: {String(h.auto_trading)}</p><p>Emergency: {String(h.emergency_stop)}</p></Card><Card title="Risk"><p>Daily loss limit configured</p><p>Max positions configured</p><p>Stop-loss & target configured</p></Card></section>
 <section className="panel"><h2>Historical Backtest</h2><p>Run the same Ichimoku rules against historical NSE or Nasdaq candles. Signals are generated on completed bars and filled at the next bar open.</p>
 <form className="backtest-form" onSubmit={runBacktest}>
  <label>Market<select value={form.market} onChange={e=>set('market',e.target.value)}><option>NSE</option><option>NASDAQ</option></select></label>
  <label>Stocks / symbols<input value={form.symbols} onChange={e=>set('symbols',e.target.value)} placeholder="RELIANCE,TCS,INFY"/></label>
  <label>Start<input type="date" value={form.start} onChange={e=>set('start',e.target.value)}/></label>
  <label>End<input type="date" value={form.end} onChange={e=>set('end',e.target.value)}/></label>
  <label>Timeframe<select value={form.interval} onChange={e=>set('interval',e.target.value)}><option value="1d">Daily</option><option value="1wk">Weekly</option><option value="1mo">Monthly</option><option value="1h">1 Hour</option><option value="30m">30 Min</option><option value="15m">15 Min</option><option value="5m">5 Min</option><option value="1m">1 Min</option></select></label>
  <label>Initial capital<input type="number" min="1" value={form.initial_capital} onChange={e=>set('initial_capital',e.target.value)}/></label>
  <label>Brokerage %<input type="number" min="0" step="0.001" value={form.brokerage_pct} onChange={e=>set('brokerage_pct',e.target.value)}/></label>
  <label>Slippage %<input type="number" min="0" step="0.001" value={form.slippage_pct} onChange={e=>set('slippage_pct',e.target.value)}/></label>
  <label>Stop-loss %<input type="number" min="0.1" step="0.1" value={form.stop_pct} onChange={e=>set('stop_pct',e.target.value)}/></label>
  <label>Target %<input type="number" min="0.1" step="0.1" value={form.target_pct} onChange={e=>set('target_pct',e.target.value)}/></label>
  <label className="check"><input type="checkbox" checked={form.allow_short} onChange={e=>set('allow_short',e.target.checked)}/> Allow short trades</label>
  <button type="submit" disabled={running}>{running?'Running…':'Run Backtest'}</button>
 </form>
 {bt&&<><div className="metrics"><Metric t="Initial" v={bt.initial_capital}/><Metric t="Final Equity" v={bt.final_equity}/><Metric t="Net Profit" v={bt.net_profit}/><Metric t="Return" v={bt.return_pct.toFixed(2)+'%'}/><Metric t="Max Drawdown" v={bt.max_drawdown_pct.toFixed(2)+'%'}/><Metric t="Trades" v={bt.total_trades}/><Metric t="Win Rate" v={bt.win_rate_pct.toFixed(2)+'%'}/><Metric t="Profit Factor" v={bt.profit_factor==null?'—':bt.profit_factor.toFixed(2)}/><Metric t="Costs" v={bt.total_costs}/></div>
 <h3>Per-symbol results</h3><div className="table-wrap"><table><thead><tr><th>Symbol</th><th>Return</th><th>Net P/L</th><th>Trades</th><th>Win rate</th><th>Max DD</th></tr></thead><tbody>{bt.symbol_results.map(r=><tr key={r.symbol}><td>{r.symbol}</td><td>{r.return_pct.toFixed(2)}%</td><td>{r.net_profit.toFixed(2)}</td><td>{r.total_trades}</td><td>{r.win_rate_pct.toFixed(2)}%</td><td>{r.max_drawdown_pct.toFixed(2)}%</td></tr>)}</tbody></table></div>
 {bt.errors?.length>0&&<p className="error">Skipped symbols: {bt.errors.map(e=>e.symbol+': '+e.error).join(' | ')}</p>}<p className="muted">{bt.data_source}. {bt.execution_model}</p></>}</section>
 <section className="panel"><h2>Architecture</h2><div className="chips">{['Frontend','Backend','Historical Data','Ichimoku Strategy','Risk Management','Broker API','Order Management','Database','Backtesting','Paper Trading','Monitoring'].map(x=><span key={x}>{x}</span>)}</div><p>This application remains in paper mode. Backtest results are historical simulations, not guarantees of future performance.</p></section>{err&&<div className="error">{err}</div>}</main></div>
}
function Card(p){return <div className="card"><h2>{p.title}</h2>{p.children}</div>}function Metric({t,v}){return <div className="metric"><small>{t}</small><strong>{typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):v}</strong></div>}
createRoot(document.getElementById('root')).render(<App/>);